window.IMOVEIS = [
  {
    "url": "https://www.jardimimobiliaria.com.br/imovel/apartamento-araraquara-2-quartos-50-m/AP0725-JARK",
    "site": "jardimimobiliaria.com.br",
    "titulo": "Apartamento com 2 dormitórios à venda, 50 m² por R$ 265.000,...",
    "tipo": "Apartamento",
    "preco": 265000,
    "condominio": 310,
    "iptu": null,
    "bairro": "Vila Velosa",
    "cidade": "Araraquara",
    "endereco": "Rua Doutor Emílio Ribas - Vila Velosa - Araraquara/SP",
    "area_util": 50,
    "area_total": null,
    "quartos": 2,
    "suites": null,
    "banheiros": 1,
    "vagas": 1,
    "caracteristicas": [],
    "descricao": "Apartamento à venda com 2 dormitórios, 1 banheiro, cozinha planejada completa em armários e 1 vaga de garagem. Ambientes amplos, bem iluminados e com ex...",
    "foto": "https://img.kenlo.io/VWRCUkQ2Tnp3d1BJRDBJVe1szkhnWr9UfpZS9ftWwjXgr7v5Znen3XVcMHllDVRJJeIbi3YwVYEtu15A8tkwo1Iem5s8ZoKz5wK7hLiTooijlkK36qn-mKz41ci6RujkmLsG1JXfG3SrkIhaHdEtYwVEUPIgHh-NRt2tZXZWhz-Spkr3duBGRkZ4+FkclxNz73mCVJSv0m8e1iKoJ8SFiDOcfKDHClpyTbMNAdsz6EIJ9xa9SUxy8h8d55m-oS7TO7S-K5+hxzlXFx5k9oa+Squ619jCLJU4Vr0lNm4L5VMZWe0S2-TJT-8+5wEDqv3JFhXchgzWgPAoc9j0Qd1IlKEKiAnCGrJJu03tzoCVgvD+b0mCZ1E9prmYrvbgPvyjSq2jOTD+1p1VosmAYssJIN3rWTZABjt1d2NLphWm7PmR+Ue9Z2ObphwVFFbfwI44uSdleApC-81OuG+4gcu8ek0=.jpg",
    "coletado_em": "2026-09-03T22:25:44.832Z"
  },
  {
    "url": "https://www.jardimimobiliaria.com.br/imovel/apartamento-araraquara-2-quartos-54-m/AP0516-JARK",
    "site": "jardimimobiliaria.com.br",
    "titulo": "Apartamento com 2 dormitórios à venda, 54 m² por R$ 270.000,...",
    "tipo": "Apartamento",
    "preco": 270000,
    "condominio": 300,
    "iptu": null,
    "bairro": "Jardim Botânico",
    "cidade": "Araraquara",
    "endereco": "Avenida Dom Carlos Carmelo - Jardim Botânico - Araraquara/SP",
    "area_util": 54,
    "area_total": null,
    "quartos": 2,
    "suites": null,
    "banheiros": 1,
    "vagas": 1,
    "caracteristicas": [
      "piscina",
      "churrasqueira",
      "portaria 24h",
      "elevador",
      "sacada",
      "playground",
      "condomínio fechado"
    ],
    "descricao": "Você está convidado a conhecer esse incrível apartamento de 2 dormitórios com uma deslumbrante cozinha planejada, moderna e funcional, com armários sob ...",
    "foto": "https://img.kenlo.io/VWRCUkQ2Tnp3d1BJRDBJVe1szkhnWr9UfpZS9ftWwjXgr7v5Znen3XVcMHllDVRJJeIbi3YwVYEtu0FoiNxNxjMRzusaU420uCfYgLiV4MbcgEeP3YL9h4mLiPP6Tevw6L0S-pTpDGW1qa5ZFvAsLF5IbvJmTzDLeNifHEdsjja2ggDsUOdMe0tH1FAqmjFC6mqyebqd01dgyxCfVu6GkDLWdoHtOlpMNOZHR9ox7ltMqBezU0J8p0oF7Jq1qTLdaOenJpi9yWxNWAZ8vJq+TqjzwtiOK59nSeUyO3cb51URUaJf1-aKA+9jrwcLou-TCwSW3hrDkec3f8vtBcFLnKsBnhDFGrNO7U-okIzD1qP5PU2CNwc-9eue-6S1bfzwSfv1diX00s8HoMmMd4dad4-xQDIVVyI6ImVCs13x6K3L+BvsNj-D9QBLCl+azoBqpjs0YBIDvsNA9XDqmcC9egCN.jpg",
    "coletado_em": "2026-09-03T22:25:47.777Z"
  },
  {
    "url": "https://www.jardimimobiliaria.com.br/imovel/apartamento-araraquara-2-quartos-52-m/AP0795-JARK",
    "site": "jardimimobiliaria.com.br",
    "titulo": "Apartamento de 52 m² na Rua Luiz Saska - Jardim Celiamar - A...",
    "tipo": "Apartamento",
    "preco": 255000,
    "condominio": 340,
    "iptu": 469.97,
    "bairro": "Jardim Celiamar",
    "cidade": "Araraquara",
    "endereco": "Rua Luiz Saska - Jardim Celiamar - Araraquara/SP",
    "area_util": 52,
    "area_total": 53,
    "quartos": 2,
    "suites": null,
    "banheiros": 1,
    "vagas": 1,
    "caracteristicas": [
      "piscina",
      "churrasqueira",
      "elevador",
      "sacada",
      "área de serviço",
      "aceita pet"
    ],
    "descricao": "APARTAMENTO À VENDA RESIDENCIAL TULIPAS II | ARARAQUARA-SP Excelente oportunidade para quem busca conforto, praticidade e ótimo custo-benefício! Apartam...",
    "foto": "https://img.kenlo.io/VWRCUkQ2Tnp3d1BJRDBJVe1szkhnWr9UfpZS9ftWwjXgr7v5Znen3XVcMHllDVRJJeIbi3YwVYEtuxo94eletzw7l+YgV6aYsRS32djE3+rCjWjGwbaPiJ-e1Nj4cs2G1KEUlJPfKUX3i7J7FsA5DGckP+wgYUL1ebycIXpMsjK8lHXzYodPfFBShx0VoBFh43SJfpao2kUQhAGbOcrCoXWoZaXlXwJWGrMNAdsz6EIJ9xa9SUxy8h8d55m-oS7TO7S-K5+hxzlXFx5k9oa+Squ619jCLJU4Vr0lNm4L5VMZWe0S2-TJT-8+5wEDqv3JFhXchgzWgPAoc9j0Qd1IlKEKiAnCGrJJu03tzoCVgvD+b0mCZ1E9prmYrvbgPvyjSq2jOTD+1p1VosmAYssJIN3rWTZABjt1d2NLphWm7PmR+Ue9Z2ObphwVFFbfwI44uSdleApC-81OuG+4gcu8ek0=.jpg",
    "coletado_em": "2026-09-03T22:25:50.676Z"
  },
  {
    "url": "https://www.jardimimobiliaria.com.br/imovel/apartamento-araraquara-2-quartos-52-m/AP0814-JARK",
    "site": "jardimimobiliaria.com.br",
    "titulo": "Apartamento de 52 m² na Rua Luiz Saska - Jardim Celiamar - A...",
    "tipo": "Apartamento",
    "preco": 320000,
    "condominio": 340,
    "iptu": 469.97,
    "bairro": "Jardim Celiamar",
    "cidade": "Araraquara",
    "endereco": "Rua Luiz Saska - Jardim Celiamar - Araraquara/SP",
    "area_util": 52,
    "area_total": 53,
    "quartos": 2,
    "suites": null,
    "banheiros": 1,
    "vagas": 1,
    "caracteristicas": [
      "área de serviço"
    ],
    "descricao": "Apartamento à venda no Residencial Tulipas II. Excelente oportunidade para quem busca conforto, praticidade e ótimo custo-benefício! Apartamento com 53 ...",
    "foto": "https://img.kenlo.io/VWRCUkQ2Tnp3d1BJRDBJVe1szkhnWr9UfpZS9ftWwjXgr7v5Znen3XVcMHllDVRJJeIbi3YwVYEtu25L6f0-xw0Hl9AQbZSwgyut7Km-vv6h8RrHyJWPv7fe-JPid-Xe8Yx61arEE1TpkpNHe98ENkVQVsN8QBjmDqyDYiBrgWixj2D-Y6pFbkFU0l0jvQ5u7mW1UrGVzHgw9xCjCKLJ8y7TabLnBkR1QPlLANk18QdW9hinR0InpwcW5JO3vSCAaKyyLIOvkiMYDwYu6oa6SeKv15TFJsonDqooL34J41sRFqAe2beFX6J24QkLuOfUB1+EkBnHl+8kYMGwXd5AnqockQ7CG7UfuUizwtbB0fesa0nSMVNu9L-J-KOzPq+gHPvsLDr6hM9XosWVLphecsfyXWMRH3QgcWpe7kKiuKOQpRbsOzvIukILHRPRztwnpXZ9YEsD8cMDpz2gisq8Nw==.jpg",
    "coletado_em": "2026-09-03T22:25:53.576Z"
  },
  {
    "url": "https://www.borsariimoveis.com.br/imovel/venda/apartamentos/araraquara/centro-edificio-regencia/17602",
    "site": "borsariimoveis.com.br",
    "titulo": "Apartamento à venda com 2 quartos no Edificio Regencia, Araraquara - Borsari Imóveis",
    "tipo": "Apartamento",
    "preco": 235000,
    "condominio": 378,
    "iptu": null,
    "bairro": "Centro",
    "cidade": "Araraquara",
    "endereco": null,
    "area_util": 30.97,
    "area_total": 92.28,
    "quartos": 2,
    "suites": null,
    "banheiros": 2,
    "vagas": 1,
    "caracteristicas": [
      "área de serviço"
    ],
    "descricao": "Apartamento na região central, com 2 quartos, sala, banheiro social, banheiro de empregada, cozinha e área de serviço.",
    "foto": "https://s3.amazonaws.com/msys-imob-borsariimoveis/imovel/fotos/17602/bbb3e0b2260ca14f94c3ae5bbfbc158bAT.jpg",
    "coletado_em": "2026-09-03T22:25:59.549Z"
  },
  {
    "url": "https://www.borsariimoveis.com.br/imovel/venda/apartamentos/araraquara/vila-girassol-villagio-harmonia/18851",
    "site": "borsariimoveis.com.br",
    "titulo": "Apartamento à venda com 2 quartos no Villagio Harmonia , Araraquara - Borsari Imóveis",
    "tipo": "Apartamento",
    "preco": 260000,
    "condominio": 474.97,
    "iptu": null,
    "bairro": "Vila Girassol",
    "cidade": "Araraquara",
    "endereco": null,
    "area_util": 50.39,
    "area_total": 108.13,
    "quartos": 2,
    "suites": null,
    "banheiros": 1,
    "vagas": 1,
    "caracteristicas": [
      "piscina",
      "playground"
    ],
    "descricao": "Apartamento em boa localização na cidade a 700 metros da padaria Pão da Terra, no bairro Harmonia, condomínio completo em lazer com piscina, coworking, lavanderia OMO, playground, apartamento padrão contendo 2 quartos, sala, cozinha e banheiro, nos quartos piso vinílico, cozinha com pedra em mármore e planejados de boa qualidade, caprichada com iluminação em led, ventiladores de teto na sala e no quarto principal, ar-condicionado também, vaga de garagem coberta.",
    "foto": "https://s3.amazonaws.com/msys-imob-borsariimoveis/imovel/fotos/18851/bb6be2e0726bc6a9363dfe4b0ac848a7AT.jpg",
    "coletado_em": "2026-09-03T22:26:05.206Z"
  },
  {
    "url": "https://www.borsariimoveis.com.br/imovel/venda/apartamentos/araraquara/jardim-das-magnolias-residencial-parque-das-tulipas/18547",
    "site": "borsariimoveis.com.br",
    "titulo": "Apartamento à venda com 2 quartos no Residencial Parque das Tulipas, Araraquara - Borsari Imóveis",
    "tipo": "Apartamento",
    "preco": 265000,
    "condominio": null,
    "iptu": null,
    "bairro": "Jardim Das Magnolias",
    "cidade": "Araraquara",
    "endereco": null,
    "area_util": 51.9,
    "area_total": 85.51,
    "quartos": 2,
    "suites": null,
    "banheiros": 1,
    "vagas": 1,
    "caracteristicas": [
      "piscina",
      "churrasqueira",
      "sacada",
      "playground"
    ],
    "descricao": "Apartamento com piso laminado, 2 quartos, cozinha planejada, banheiro social com armários, espelho e box. \r\nGaragem coberta na entrada do bloco. Sacada grande. O condomínio conta com piscina, 2 quiosques com churrasqueira, playground e bibicletário. \r\nLocalização privilegiada.",
    "foto": "https://s3.amazonaws.com/msys-imob-borsariimoveis/imovel/fotos/18547/f29ba479342fb3223394bf7cced4e7c3AT.jpg",
    "coletado_em": "2026-09-03T22:26:10.732Z"
  },
  {
    "url": "https://www.borsariimoveis.com.br/imovel/venda/apartamentos/araraquara/residencial-cambuy-vistas-do-botanico-cedros/18884",
    "site": "borsariimoveis.com.br",
    "titulo": "Apartamento à venda com 2 quartos no  Vistas do Botânico Cedros , Araraquara - Borsari Imóveis",
    "tipo": "Apartamento",
    "preco": 277000,
    "condominio": 380,
    "iptu": null,
    "bairro": "Residencial Cambuy",
    "cidade": "Araraquara",
    "endereco": null,
    "area_util": 51.88,
    "area_total": 94.18,
    "quartos": 2,
    "suites": null,
    "banheiros": 1,
    "vagas": 1,
    "caracteristicas": [
      "piscina",
      "churrasqueira",
      "playground",
      "salão de festas",
      "salão de jogos",
      "ar condicionado"
    ],
    "descricao": "Imóvel muito bem localizado, no bairro Cambui, metragem diferenciada de 51,88m², cozinha com planejados, novos com fino acabamento, 2 quartos, sendo 1 deles com planejados, ar condicionado, condomínio distinto com jacuzzi externa, piscina, lavanderia com máquinas lava e seca, playground, sala de jogos, salão de festas com churrasqueira.",
    "foto": "https://s3.amazonaws.com/msys-imob-borsariimoveis/imovel/fotos/18884/3e6397479a7a25b9afd38b86d821991bAT.jpg",
    "coletado_em": "2026-09-03T22:26:16.121Z"
  },
  {
    "url": "https://www.borsariimoveis.com.br/imovel/venda/apartamentos/araraquara/residencial-cambuy-vistas-do-botanico-cedros/18308",
    "site": "borsariimoveis.com.br",
    "titulo": "Apartamento à venda com 2 quartos no  Vistas do Botânico Cedros , Araraquara - Borsari Imóveis",
    "tipo": "Apartamento",
    "preco": 230000,
    "condominio": 382,
    "iptu": null,
    "bairro": "Residencial Cambuy",
    "cidade": "Araraquara",
    "endereco": null,
    "area_util": 43,
    "area_total": 98.67,
    "quartos": 2,
    "suites": null,
    "banheiros": 1,
    "vagas": 1,
    "caracteristicas": [
      "piscina",
      "academia",
      "sacada",
      "playground",
      "salão de festas"
    ],
    "descricao": "Apartamento no oitavo andar, com sacada, 2 dormitórios em piso de carpete de madeira laminado, banheiro social com box blindex, sala para 2 ambientes, cozinha e lavanderia integrada.\r\nPrédio com piscina adulto e infantil, SPA, sauna, academia, salão de festas, Playground, lavanderia espaço para churrasco e mercado 24hs.",
    "foto": "https://s3.amazonaws.com/msys-imob-borsariimoveis/imovel/fotos/18308/e8f71b1ef1df7c56f1cab72557794b1aAT.jpg",
    "coletado_em": "2026-09-03T22:26:21.662Z"
  },
  {
    "url": "https://www.borsariimoveis.com.br/imovel/venda/apartamentos/araraquara/jardim-botanico-parque-dos-jequitibas/18838",
    "site": "borsariimoveis.com.br",
    "titulo": "Apartamento à venda com 2 quartos no Parque dos Jequitibás , Araraquara - Borsari Imóveis",
    "tipo": "Apartamento",
    "preco": 280000,
    "condominio": 245,
    "iptu": null,
    "bairro": "Jardim Botanico",
    "cidade": "Araraquara",
    "endereco": null,
    "area_util": 51,
    "area_total": 53.34,
    "quartos": 2,
    "suites": null,
    "banheiros": 1,
    "vagas": 2,
    "caracteristicas": [
      "sacada",
      "área de serviço"
    ],
    "descricao": "Excelente apartamento localizado no 15º andar, em área nobre e super arborizada da cidade, possui 2 quartos, sala, sacada, banheiro social, cozinha ampla, área de serviço e condomínio com lazer completo.",
    "foto": "https://s3.amazonaws.com/msys-imob-borsariimoveis/imovel/fotos/18838/bf8db40f00e43bd21021826bc100cf6cAT.jpg",
    "coletado_em": "2026-09-03T22:26:26.999Z"
  },
  {
    "url": "https://www.borsariimoveis.com.br/imovel/venda/apartamentos/araraquara/jardim-gardenias-parque-das-violetas/17149",
    "site": "borsariimoveis.com.br",
    "titulo": "Apartamento à venda com 2 quartos no Parque das Violetas, Araraquara - Borsari Imóveis",
    "tipo": "Apartamento",
    "preco": 220000,
    "condominio": 295.35,
    "iptu": null,
    "bairro": "Jardim Gardênias",
    "cidade": "Araraquara",
    "endereco": null,
    "area_util": 39.3,
    "area_total": 85.51,
    "quartos": 2,
    "suites": null,
    "banheiros": 1,
    "vagas": 1,
    "caracteristicas": [
      "varanda"
    ],
    "descricao": "Apartamento com 2 quartos, sala para 2 ambientes, banheiro, cozinha e lavanderia integrada e varanda.\r\nÁrea de lazer completa e com localização privilegiada.",
    "foto": "https://s3.amazonaws.com/msys-imob-borsariimoveis/imovel/fotos/17149/ad00210274e9b825c249d841ba3b100dAT.jpg",
    "coletado_em": "2026-09-03T22:26:32.265Z"
  },
  {
    "url": "https://www.borsariimoveis.com.br/imovel/venda/apartamentos/araraquara/jardim-magnolias-residencial-tulipas/18768",
    "site": "borsariimoveis.com.br",
    "titulo": "Apartamento à venda com 2 quartos no Residencial Tulipas, Araraquara - Borsari Imóveis",
    "tipo": "Apartamento",
    "preco": 260000,
    "condominio": 350,
    "iptu": null,
    "bairro": "Jardim Magnólias",
    "cidade": "Araraquara",
    "endereco": null,
    "area_util": 51.9,
    "area_total": 85.51,
    "quartos": 2,
    "suites": null,
    "banheiros": 1,
    "vagas": 1,
    "caracteristicas": [
      "elevador",
      "varanda"
    ],
    "descricao": "Excelente apartamento localizado no 3º andar, com acesso por elevador.\r\nO imóvel conta com uma sala de TV e jantar integradas.\r\nA cozinha possui armários planejados, integrada a lavanderia.\r\n2 dormitórios e 1 banheiro social.\r\n1 vaga de garagem coberta, localizada logo abaixo da varanda.\r\nO apartamento recebe o sol da tarde, porém um edifício vizinho proporciona sombra parcial.",
    "foto": "https://s3.amazonaws.com/msys-imob-borsariimoveis/imovel/fotos/18768/842855b2ac53ee97bdd6da46c1d8367bAT.jpg",
    "coletado_em": "2026-09-03T22:26:37.753Z"
  },
  {
    "url": "https://www.chavesnamao.com.br/imovel/apartamento-a-venda-2-quartos-com-garagem-sp-araraquara-residencial-cambuy-51m2-RS280000/id-46205424/",
    "site": "chavesnamao.com.br",
    "titulo": "Apartamento para venda em Residencial Cambuy de 51.00m² com 2 Quartos e 1 Garagem",
    "tipo": "Apartamento",
    "preco": 280000,
    "condominio": 487,
    "iptu": null,
    "bairro": "Residencial Cambuy",
    "cidade": null,
    "endereco": null,
    "area_util": 51,
    "area_total": 56,
    "quartos": 2,
    "suites": null,
    "banheiros": 2,
    "vagas": 1,
    "caracteristicas": [
      "piscina",
      "academia",
      "elevador",
      "sacada",
      "mobiliado",
      "playground",
      "salão de festas",
      "condomínio fechado"
    ],
    "descricao": "Código do Imóvel: CM1980847-1 - Imóvel anunciado por Vivaz Soluções Imobiliárias - CRECI J45121, atráves da plataforma Leads4Sales. Vista privilegiada, praticidade no dia a dia e a oportunidade de morar em um dos condomínios mais procurados da região  Imagine chegar em casa todos os dias e desfrutar de uma vista privilegiada do 14º andar, com a tranquilidade de um condomínio moderno, completo e pronto para morar. Este apartamento no Vistas do Botânico Cedros reúne conforto, funcionalidade e excelente potencial de valorização para quem busca o primeiro imóvel, deseja investir ou conquistar mais qualidade de vida.  Com ambientes bem distribuídos, sacada, garagem coberta e documentação totalmente regularizada, o imóvel está desocupado e pronto para receber seu novo proprietário.  Características do Imóvel 51,12 m² de área privativa 2 dormitórios Sala de estar e jantar integradas Cozinha funcional Banheiro social Sacada 14º andar 1 vaga de garagem coberta Imóvel quitado Documentação em ordem Aceita financiamento Apartamento desocupado Estrutura do Condomínio  Localizado no Vistas do Botânico Cedros, empreendimento da Vitta Residencial, o condomínio oferece infraestrutura moderna e áreas de convivência pensadas para toda a família. Entre os diferenciais estão elevador, complexo aquático, espaço fitness, salão de festas, coworking, playground, lavanderia compartilhada e áreas de convivência integradas.  Localização Estratégica  Situado na Rua Antônio Fernandes, nº 251, no Residencial Cambuy, o empreendimento está em uma região em constante desenvolvimento e valorização, com fácil acesso aos principais corredores viários de Araraquara. A localização proporciona praticidade para deslocamentos diários, além da proximidade com comércios, serviços e áreas de lazer da cidade.  Potencial de Valorização  O Vistas do Botânico Cedros tornou-se uma referência entre os empreendimentos mais procurados da região, destacando-se por oferecer apartamentos com sacada, lazer completo e excelente custo-benefício. Sua combinação de localização, infraestrutura e padrão construtivo favorece a valorização patrimonial ao longo dos anos.  FAQ  O imóvel aceita financiamento? Sim. A documentação está regularizada e apta para financiamento bancário.  O apartamento está ocupado? Não. O imóvel encontra-se desocupado e disponível para visitas.  Possui vaga de garagem? Sim. Conta com 1 vaga de garagem coberta.  Qual o valor do condomínio? R$ 487,00 mensais.  Valor de Venda  R$ 280.000,00  Vivaz Soluções Imobiliárias  A Vivaz Soluções Imobiliárias conecta pessoas aos melhores imóveis de Araraquara e região, oferecendo atendimento consultivo, segurança jurídica e acompanhamento completo em todas as etapas da negociação. Uma excelente oportunidade para quem procura Apartamento à venda em Arara   Atualizado por Imobiliária Vivaz ",
    "foto": "https://www.chavesnamao.com.br/imn/0850x0450/N/60/imoveis/504348/46205424/sp-araraquara-residencial-cambuy-rua-antonio-fernandes-apartamento-a-venda-2-quartos-6a92caf7-1.jpg",
    "coletado_em": "2026-09-03T22:26:40.564Z"
  },
  {
    "url": "https://www.chavesnamao.com.br/imovel/apartamento-a-venda-2-quartos-com-garagem-sp-araraquara-vila-harmonia-99m2-RS250000/id-44711546/",
    "site": "chavesnamao.com.br",
    "titulo": "Apartamento com 2 quartos à venda na Rua Caetano Nigro, 1212, Vila Harmonia, Araraquara",
    "tipo": "Apartamento",
    "preco": 250000,
    "condominio": 454,
    "iptu": 39,
    "bairro": "Vila Harmonia",
    "cidade": null,
    "endereco": null,
    "area_util": 46,
    "area_total": 99.03,
    "quartos": 2,
    "suites": null,
    "banheiros": 2,
    "vagas": 1,
    "caracteristicas": [
      "piscina",
      "churrasqueira",
      "academia",
      "portaria 24h",
      "elevador",
      "playground",
      "salão de festas",
      "salão de jogos",
      "quadra"
    ],
    "descricao": "Apresentando este apartamento padrão localizado no bairro Vila Harmonia, em Araraquara. Com apenas 2 anos de construção, este imóvel possui 99,03 m² de área total e 45,92 m² de área útil.  O apartamento está localizado no Edifício Villagio Harmonia, um empreendimento moderno e bem cuidado, com diversas comodidades como churrasqueira, piscina, playground, salão de festas, quadra poliesportiva, brinquedoteca, academia e muito mais. O imóvel conta ainda com 02 dormitórios, sala para 02 ambientes, banheiro social, cozinha planejada, lavanderia e 01 vaga de garagem proporcionando conforto e praticidade ao morador.  Este apartamento é uma excelente oportunidade para quem deseja investir ou adquirir um imóvel próprio.   Venha conhecer pessoalmente este apartamento e descubra todas as vantagens que ele pode oferecer. Agende uma visita e conheça seu novo lar!",
    "foto": "https://www.chavesnamao.com.br/imn/0850x0450/N/60/imoveis/1336555/44711546/sp-araraquara-vila-harmonia-rua-caetano-nigro-apartamento-a-venda-2-quartos-6a57a679-1.jpg",
    "coletado_em": "2026-09-03T22:26:43.364Z"
  },
  {
    "url": "https://www.chavesnamao.com.br/imovel/apartamento-a-venda-2-quartos-com-garagem-sp-araraquara-vila-harmonia-103m2-RS260000/id-46239951/",
    "site": "chavesnamao.com.br",
    "titulo": "Apartamento para venda em Vila Harmonia de 48.00m² com 2 Quartos e 1 Garagem",
    "tipo": "Apartamento",
    "preco": 260000,
    "condominio": null,
    "iptu": 374,
    "bairro": "Vila Harmonia",
    "cidade": null,
    "endereco": null,
    "area_util": 48,
    "area_total": 103,
    "quartos": 2,
    "suites": null,
    "banheiros": 2,
    "vagas": 1,
    "caracteristicas": [
      "piscina",
      "churrasqueira",
      "academia",
      "elevador",
      "área de serviço",
      "playground",
      "salão de festas",
      "quadra",
      "condomínio fechado"
    ],
    "descricao": "Código do Imóvel: CM1845614-9 - Imóvel anunciado por Imperio Imoveis Araraquara - CRECI 37916, atráves da plataforma Leads4Sales. Apartamento no Condomínio Villagio Harmonia com 2 Dormitórios, 1 Banheiro com Box de Vidro, Sala, 1 Cozinha com Armários Planejados, Área de Serviço, Sol da Manhã, Apartamento Inteiro com Sanca de Gesso, 1 Vaga de Garagem Demarcada e Coberta. * Prédio Conta com Portaria 24 Hs, Elevador, Piscina Adulto e Infantil, Mini Mercado 24 Hs, 02 Churrasqueiras, Playground, Quadra de Futebol, Academia, Salão de Festa, Pet Place, Lavanderia, Movie Games, Coworking, as Vagas de Garagem estão em Processo de Cobertura. * Excelente Localização, Próximo à Padaria Pão da Terra, Jaú Serve Supermercados, Astral Energia Solar e Piscinas, Via Saudável. * Aceita Financiamento Bancário. * Valores e Disponibilidade Sujeito a Alteração sem Aviso Prévio.   Atualizado por Imperio imóveis Araraquara ",
    "foto": "https://www.chavesnamao.com.br/imn/0850x0450/N/60/imoveis/504348/46239951/sp-araraquara-vila-harmonia-rua-rolando-lupo-apartamento-a-venda-2-quartos-6a957382-1.jpg",
    "coletado_em": "2026-09-03T22:26:46.152Z"
  },
  {
    "url": "https://www.chavesnamao.com.br/imovel/apartamento-a-venda-2-quartos-com-garagem-sp-araraquara-parque-residencial-vale-do-sol-58m2-RS240000/id-25434820/",
    "site": "chavesnamao.com.br",
    "titulo": "Apartamento à venda 2 quartos no Edifício Parque do Sol - Araraquara / SP",
    "tipo": "Apartamento",
    "preco": 240000,
    "condominio": null,
    "iptu": 300,
    "bairro": null,
    "cidade": null,
    "endereco": null,
    "area_util": 58,
    "area_total": null,
    "quartos": 2,
    "suites": null,
    "banheiros": 2,
    "vagas": 1,
    "caracteristicas": [
      "elevador",
      "playground"
    ],
    "descricao": "02 dormitórios Sala Cozinha Banheiro Lavanderia Bicicletário Mercadinho Garagem 01 vaga",
    "foto": "https://www.chavesnamao.com.br/imn/0850x0450/N/60/imoveis/272165/25434820/sp-araraquara-avenida-maria-antonia-camargo-de-oliveira-apartamento-a-venda-2-quartos-69c7ff2d-1.jpg",
    "coletado_em": "2026-09-03T22:26:48.912Z"
  },
  {
    "url": "https://www.chavesnamao.com.br/imovel/apartamento-a-venda-2-quartos-com-garagem-sp-araraquara-jardim-botanico-88m2-RS250000/id-45251314/",
    "site": "chavesnamao.com.br",
    "titulo": "Condomínio Residencial Antares - Apartamento à venda no Condomínio Antares | Jardim Botânico",
    "tipo": "Apartamento",
    "preco": 250000,
    "condominio": 350,
    "iptu": 28,
    "bairro": "Jardim Botânico",
    "cidade": null,
    "endereco": null,
    "area_util": 55,
    "area_total": 88.14,
    "quartos": 2,
    "suites": null,
    "banheiros": 2,
    "vagas": 1,
    "caracteristicas": [
      "piscina",
      "churrasqueira",
      "mobiliado",
      "área de serviço",
      "playground",
      "salão de festas",
      "condomínio fechado"
    ],
    "descricao": "Apartamento à venda no Condomínio Antares | Jardim Botânico  Descrição Geral: 2 dormitórios Sala de Estar integrada à Sala de Jantar Cozinha Integrado à área de Serviço 1 Banheiros 1 Vaga de Garagem    Acabamentos Detalhes Técnicos: Apartamento com Pintura Nova e detalhes em cimento queimado Móveis Planejados em todos os ambientes de alta qualidade Cristaleira com Iluminação em Led Iluminação Personalizada Piso Vinílico na Sala e Dormitórios Banheiro e Cozinha com porcelanato Cozinha com Cooktop Dormitório com Espelho e Penteadeira com iluminação em led   Dimensões: Área Total 88,14 m² Área Construída 55,56 m²   Investimento para aquisição deste imóvel:  Valor do Imóvel: R$ 250.000,00 Valor do Condomínio: R$ 350,00 Valor do Iptu: R$ 28,96 Aceita financiamento     Agende sua visita! Morabito Negócios Imobiliários (16) 9       (link removido)  br. Rua Padre Duarte, 1393 – Ed. Morabito, Sala 63, Centro, Araraquara/SP CRECI/SP 045472-J Informações sujeitas a alterações. Consulte o corretor responsável.    Chave do anúncio: f1Y6bwcFMoMKKZHv",
    "foto": "https://www.chavesnamao.com.br/imn/0850x0450/N/60/imoveis/1172248/45251314/sp-araraquara-jardim-botanico-avenida-dom-carlos-carmelo-apartamento-a-venda-2-quartos-6a6cabba-1.jpg",
    "coletado_em": "2026-09-03T22:26:51.697Z"
  },
  {
    "url": "https://www.chavesnamao.com.br/imovel/apartamento-a-venda-2-quartos-com-garagem-sp-araraquara-vila-harmonia-50m2-RS250000/id-45203035/",
    "site": "chavesnamao.com.br",
    "titulo": "Apartamento com 2 quartos à venda na Rua Caetano Nigro, 1212, Vila Harmonia, Araraquara",
    "tipo": "Apartamento",
    "preco": 250000,
    "condominio": 370,
    "iptu": 41,
    "bairro": "Vila Harmonia",
    "cidade": null,
    "endereco": null,
    "area_util": 50,
    "area_total": 92,
    "quartos": 2,
    "suites": null,
    "banheiros": 2,
    "vagas": 1,
    "caracteristicas": [],
    "descricao": "2 dormitorios, sala para dois ambientes, banheiro com gabinete, cozinha com armarios, area de servico, 01 vaga de garagem descoberta.",
    "foto": "https://www.chavesnamao.com.br/imn/0850x0450/N/60/imoveis/1379419/45203035/sp-araraquara-vila-harmonia-rua-caetano-nigro-apartamento-a-venda-2-quartos-6a6b53eb-1.jpg",
    "coletado_em": "2026-09-03T22:26:54.465Z"
  },
  {
    "url": "https://www.chavesnamao.com.br/imovel/apartamento-a-venda-2-quartos-com-garagem-sp-araraquara-vila-harmonia-98m2-RS175000/id-43090069/",
    "site": "chavesnamao.com.br",
    "titulo": "O apartamento que faz voce querer mudar antes mesmo da visita!",
    "tipo": "Apartamento",
    "preco": 175000,
    "condominio": 352,
    "iptu": null,
    "bairro": "Vila Harmonia",
    "cidade": null,
    "endereco": null,
    "area_util": 65,
    "area_total": 98,
    "quartos": 2,
    "suites": null,
    "banheiros": 2,
    "vagas": 1,
    "caracteristicas": [
      "piscina"
    ],
    "descricao": "Existe algo especial nos imoveis que conseguem transmitir sensacao de lar logo no primeiro olhar. Este apartamento no Residencial Antares foi pensado para quem valoriza conforto, praticidade e ambientes que tornam a rotina mais leve e agradavel. A integracao entre sala e cozinha cria um espaco moderno e acolhedor, perfeito para viver bons momentos no dia a dia. Conta com 2 dormitorios, cozinha conjugada com armario, banheiro com gabinete e box, alem de ambientes muito bem distribuidos. O condominio oferece piscina, espaco gourmet, bicicletario e um ambiente tranquilo em excelente localizacao. Um imovel que une aconchego, funcionalidade e aquela sensacao gostosa de ter encontrado o lugar certo.",
    "foto": "https://www.chavesnamao.com.br/imn/0850x0450/N/60/imoveis/300147/43090069/sp-araraquara-vila-harmonia-rua-doutor-walter-medeiros-mauro-apartamento-a-venda-2-quartos-6a18212b-1.jpg",
    "coletado_em": "2026-09-03T22:26:57.260Z"
  }
];
